completed ticket 8
manheicatherine/frontend-nc-news pull request #6
Opened 2023-02-09 08:52 UTC by manheicatherine

2023-02-09 09:15 UTC, itskatherine requested changes
Hi Catherine, a great start but a few things to look at below 
Have a go at addressing my comments and submit another PR once you have please 🙂

2023-02-09 09:15 UTC, itskatherine commented on src/components/AddComments.jsx
> +
Though you have posted the comment successfully to the database, it's not updating on the page (something which you're covering by asking the user to refresh the page)
However we can't be asking the user to refresh every time, what we need to do is use state to update the comments following a successful post request.
So we post the comment to the db, and then update the comments state so it includes the new posted comment
Can you please add this and then resubmit this PR

2023-02-09 09:15 UTC, itskatherine commented on src/components/AddComments.jsx
> +          alert("Please enter a correct username or valid comments. Please refresh the page.");
Try to avoid using alerts/pop ups, many browsers block them

2023-02-09 09:15 UTC, itskatherine commented on src/components/AddComments.jsx
> +      setIsPost(true);
If we want to set isPosted to true after a post has happened successfully, this line should go in the .then block that follows a successful post

2023-02-09 09:15 UTC, itskatherine commented on src/utils/api.js
> +  console.log(body)
Remember to get rid of console logs for PRs 🙂

2023-02-09 09:15 UTC, itskatherine commented on src/components/AddComments.jsx
> +
The info that has been typed into your comment box is remaining after you press the submit button.
Remember than text input boxes are [controlled components](https://notes.northcoders.com/courses/js-front-end/controlled-components), and will need a state for the text being input into the form element, which will be transferred over to your newComment state on submitting.

2023-02-10 09:41 UTC, elijaharley approved these changes
Great stuff Catherine, the functionality is really nice on here now, and the comment displays immediately, giving feedback to the user that they have succeeded.

2023-02-10 09:45 UTC, merged